[project]
name = "src"
version = "0.0.0"
description = ""
authors = [{ name = "Yuyan Chen, Othmane Echchabi", email = "you@example.com" }]
requires-python = ">=3.12,<3.13"
readme = "README.md"
license = "MIT"
dependencies = [
    "accelerate>=1.13.0",
    "datasets>=4.8.4",
    "ddgs>=9.12.0",
    "opencv-python>=4.13.0.92",
    "pre-commit>=4.2.0,<5",
    "pybioclip>=2.1.1",
    "qwen-agent[code-interpreter,gui,mcp,rag]>=0.0.34",
    "soundfile>=0.13.1",
    "torch>=2.10.0",
    "torchvision>=0.25.0",
    "transformers>=5.3.0",
]

[dependency-groups]
dev = []

[project.optional-dependencies]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


#
# Scripts
#
[project.scripts]

#
# Tools
#

[tool.autoflake]
remove-all-unused-imports = true
in-place = true
ignore-init-module-imports = true
remove-unused-variables = true
recursive = true

[tool.autopep8]
max_line_length = 120
in-place = true
aggressive = 2
ignore = ["W503", "E203", "E501"]
recursive = true

[tool.flake8]
max-line-length = 120
ignore = ["E203", "E266", "E501", "W503"]
docstring-convention = "numpy"
max-complexity = 20
per-file-ignores = []
exclude = [
    ".git",
    "migrations",
    "__pycache__"
]

[tool.pylint]
disable = "C0114,C0115,C0116,R0903,R1710,W1203"
max-line-length = 120
max-locals = 20
max-args = 16
max-positional-arguments = 16
max-attributes = 20

[tool.black]
line-length = 120
target-version = ["py312"]

[tool.isort]
profile = "black"

[tool.flynt]
line-length = 120
transform-concats = true
verbose = true

[tool.docformatter]
style = "numpy"
pre-summary-newline = true
wrap-descriptions = 120
wrap-summaries = 120
blank = false
exclude = []
recursive = true
